/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-12-02 17:10:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Foodie - Supper delicious Burger in town!</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- \r\n");
      out.write("    - favicon\r\n");
      out.write("  -->\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"favicon.svg\" type=\"image/svg+xml\">\r\n");
      out.write("\r\n");
      out.write("  <!-- \r\n");
      out.write("    - custom css link\r\n");
      out.write("  -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- \r\n");
      out.write("    - google font link\r\n");
      out.write("  -->\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("  <link\r\n");
      out.write("    href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&family=Rubik:wght@400;500;600;700&family=Shadows+Into+Light&display=swap\"\r\n");
      out.write("    rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- \r\n");
      out.write("    - preload images\r\n");
      out.write("  -->\r\n");
      out.write("  <link rel=\"preload\" as=\"image\" href=\"image/hero-banner.png\" media=\"min-width(768px)\">\r\n");
      out.write("  <link rel=\"preload\" as=\"image\" href=\"image/hero-banner-bg.png\" media=\"min-width(768px)\">\r\n");
      out.write("  <link rel=\"preload\" as=\"image\" href=\"image/hero-bg.jpg\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"top\">\r\n");
      out.write("<!-- \r\n");
      out.write("    - #HEADER\r\n");
      out.write("  -->\r\n");
      out.write("\r\n");
      out.write("  <header class=\"header\" data-header>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      <h1>\r\n");
      out.write("        <a href=\"#\" class=\"logo\">Foodie<span class=\"span\">.</span></a>\r\n");
      out.write("      </h1>\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"navbar\" data-navbar>\r\n");
      out.write("        <ul class=\"navbar-list\">\r\n");
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"#home\" class=\"navbar-link\" data-nav-link>Home</a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"#banner\" class=\"navbar-link\" data-nav-link>Special Offers</a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"#food-menu\" class=\"navbar-link\" data-nav-link>Menu</a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"#contact\" class=\"navbar-link\" data-nav-link>Contact Us</a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"logout\" class=\"navbar-link\">Logout</a>\r\n");
      out.write("          \r\n");
      out.write("  </li>\r\n");
      out.write("  \r\n");
      out.write("  </li>\r\n");
      out.write("        <li class=\"nav-item bg-danger\">\r\n");
      out.write("          <a href=\"logout\" class=\"navbar-link\">Welcome, ");
      out.print( session.getAttribute("name") );
      out.write("</a>\r\n");
      out.write("          \r\n");
      out.write("  </li>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("  \r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        <button class=\"nav-toggle-btn\" aria-label=\"Toggle Menu\" data-menu-toggle-btn>\r\n");
      out.write("          <span class=\"line top\"></span>\r\n");
      out.write("          <span class=\"line middle\"></span>\r\n");
      out.write("          <span class=\"line bottom\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <main>\r\n");
      out.write("    <article>\r\n");
      out.write("\r\n");
      out.write("      <!-- \r\n");
      out.write("        - #HERO\r\n");
      out.write("      -->\r\n");
      out.write("\r\n");
      out.write("      <section class=\"hero\" id=\"home\" style=\"background-image: url('image/hero-bg.jpg')\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"hero-content\">\r\n");
      out.write("\r\n");
      out.write("            <p class=\"hero-subtitle\">Eat Sleep And</p>\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"h1 hero-title\">Supper delicious Burger in town!</h2>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"hero-text\">Food is any substance consumed to provide nutritional support for an organism.</p>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"btn\">Order Now</button>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <figure class=\"hero-banner\">\r\n");
      out.write("            <img src=\"image/hero-banner-bg.png\" width=\"820\" height=\"716\" alt=\"\" aria-hidden=\"true\"\r\n");
      out.write("              class=\"w-100 hero-img-bg\">\r\n");
      out.write("\r\n");
      out.write("            <img src=\"image/hero-banner.png\" width=\"700\" height=\"637\" loading=\"lazy\" alt=\"Burger\"\r\n");
      out.write("              class=\"w-100 hero-img\">\r\n");
      out.write("          </figure>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- \r\n");
      out.write("        - #FOOD MENU\r\n");
      out.write("      -->\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("          <!-- \r\n");
      out.write("        - #BANNER\r\n");
      out.write("      -->\r\n");
      out.write("\r\n");
      out.write("      <section class=\"section section-divider gray banner\" id=\"banner\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("          <ul class=\"banner-list\">\r\n");
      out.write("\r\n");
      out.write("            <li class=\"banner-item banner-lg\">\r\n");
      out.write("              <div class=\"banner-card\">\r\n");
      out.write("\r\n");
      out.write("                <img src=\"image/banner-1.jpg\" width=\"550\" height=\"450\" loading=\"lazy\"\r\n");
      out.write("                  alt=\"Discount For Delicious Tasty Burgers!\" class=\"banner-img\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"banner-item-content\">\r\n");
      out.write("                  <p class=\"banner-subtitle\">50% Off Now!</p>\r\n");
      out.write("\r\n");
      out.write("                  <h3 class=\"banner-title\">Discount For Delicious Tasty Noodles!</h3>\r\n");
      out.write("\r\n");
      out.write("                  <p class=\"banner-text\">Sale off 50% only this week</p>\r\n");
      out.write("\r\n");
      out.write("                  <button class=\"btn\">Order Now</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"banner-item banner-sm\">\r\n");
      out.write("              <div class=\"banner-card\">\r\n");
      out.write("\r\n");
      out.write("                <img src=\"image/banner-2.jpg\" width=\"550\" height=\"465\" loading=\"lazy\" alt=\"Delicious Pizza\"\r\n");
      out.write("                  class=\"banner-img\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"banner-item-content\">\r\n");
      out.write("                  <h3 class=\"banner-title\">Delicious Pizza</h3>\r\n");
      out.write("\r\n");
      out.write("                  <p class=\"banner-text\">50% off Now</p>\r\n");
      out.write("\r\n");
      out.write("                  <button class=\"btn\">Order Now</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"banner-item banner-sm\">\r\n");
      out.write("              <div class=\"banner-card\">\r\n");
      out.write("\r\n");
      out.write("                <img src=\"image/banner-3.jpg\" width=\"550\" height=\"465\" loading=\"lazy\" alt=\"American Burgers\"\r\n");
      out.write("                  class=\"banner-img\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"banner-item-content\">\r\n");
      out.write("                  <h3 class=\"banner-title\">American Burgers</h3>\r\n");
      out.write("\r\n");
      out.write("                  <p class=\"banner-text\">50% off Now</p>\r\n");
      out.write("\r\n");
      out.write("                  <button class=\"btn\">Order Now</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"banner-item banner-md\">\r\n");
      out.write("              <div class=\"banner-card\">\r\n");
      out.write("\r\n");
      out.write("                <img src=\"image/banner-4.jpg\" width=\"550\" height=\"220\" loading=\"lazy\" alt=\"Tasty Buzzed Pizza\"\r\n");
      out.write("                  class=\"banner-img\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"banner-item-content\">\r\n");
      out.write("                  <h3 class=\"banner-title\">Tasty Buzzed Pizza</h3>\r\n");
      out.write("\r\n");
      out.write("                  <p class=\"banner-text\">Sale off 50% only this week</p>\r\n");
      out.write("\r\n");
      out.write("                  <button class=\"btn\">Order Now</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </article>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- \r\n");
      out.write("    - #FOOTER\r\n");
      out.write("  -->\r\n");
      out.write("\r\n");
      out.write("  <footer class=\"footer\" id=\"contact\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-top\" style=\"background-image: url('image/footer-illustration.png')\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-brand\">\r\n");
      out.write("\r\n");
      out.write("          <a href=\"\" class=\"logo\">Foodie<span class=\"span\">.</span></a>\r\n");
      out.write("\r\n");
      out.write("          <p class=\"footer-text\">\r\n");
      out.write("            Financial experts support or help you to to find out which way you can raise your funds more.\r\n");
      out.write("          </p>\r\n");
      out.write("\r\n");
      out.write("          <ul class=\"social-list\">\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\" class=\"social-link\">\r\n");
      out.write("                <ion-icon name=\"logo-facebook\"></ion-icon>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\" class=\"social-link\">\r\n");
      out.write("                <ion-icon name=\"logo-twitter\"></ion-icon>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\" class=\"social-link\">\r\n");
      out.write("                <ion-icon name=\"logo-instagram\"></ion-icon>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"footer-list\">\r\n");
      out.write("\r\n");
      out.write("          <li>\r\n");
      out.write("            <p class=\"footer-list-title\">Contact Info</p>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li>\r\n");
      out.write("            <p class=\"footer-list-item\">+91 6289554873</p>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li>\r\n");
      out.write("            <p class=\"footer-list-item\">Foodie@gmail.com</p>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li>\r\n");
      out.write("            <address class=\"footer-list-item\">Maichel Nagar Road Kolkata-700133</address>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-bottom\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <p class=\"copyright-text\">\r\n");
      out.write("          &copy; 2024 <a href=\"#\" class=\"copyright-link\">Foodie</a> All Rights Reserved.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- \r\n");
      out.write("    - #BACK TO TOP\r\n");
      out.write("  -->\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#top\" class=\"back-top-btn\" aria-label=\"Back to top\" data-back-top-btn>\r\n");
      out.write("    <ion-icon name=\"chevron-up\"></ion-icon>\r\n");
      out.write("  </a>\r\n");
      out.write("\r\n");
      out.write("  <!-- \r\n");
      out.write("    - custom js link\r\n");
      out.write("  -->\r\n");
      out.write("  <script src=\"script.js\" defer></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- \r\n");
      out.write("    - ionicon link\r\n");
      out.write("  -->\r\n");
      out.write("  <script type=\"module\" src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js\"></script>\r\n");
      out.write("  <script nomodule src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
